# Generated by Django 3.1 on 2021-01-18 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 1, 18, 19, 36, 8, 562917, tzinfo=utc), editable=False),
        ),
    ]
